### ISSUE TITLE
Incompatibility with 3.0.9 

### ISSUE THREAD

**Issue by leperse** [egeloen/IvoryLuceneSearchBundle#14]
Hello,

I'm struggling to install this bundle on Symfony **3.0.9**, guess the **zendframework/zendsearch** library is incompatible with this version of Symfony.

**Comment by egeloen** [comment]
Can you copy/paste the composer errors?

**Comment by leperse** [comment]
**Here is the composer errors :**

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/framework-bundle v2.0.18 requires symfony/dependency-injection v2.0.18 -> no matching package found.
    - symfony/framework-bundle v2.0.17 requires symfony/dependency-injection v2.0.17 -> no matching package found.
    - symfony/framework-bundle 2.0.7 requires symfony/translator 2.0.7 -> no matching package found.
    - Conclusion: remove symfony/symfony v3.0.9
    - Conclusion: don't install symfony/symfony v3.0.9
    - Conclusion: don't install symfony/symfony v3.0.8
    - Conclusion: don't install symfony/symfony v3.0.7
    - Conclusion: don't install symfony/symfony v3.0.6
    - Conclusion: don't install symfony/symfony v3.0.5
    - Conclusion: don't install symfony/symfony v3.0.4
    - Conclusion: don't install symfony/symfony v3.0.3
    - Conclusion: don't install symfony/symfony v3.0.2
    - Conclusion: don't install symfony/symfony v3.0.1
    - egeloen/lucene-search-bundle 1.0.3 requires symfony/framework-bundle ~2.0 -> satisfiable by symfony/framework-bundle[2.0.7, v2.0.10, v
2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.18, v2.0.19, v2.0.20, v2.0.21, v2.0.22, v2.0.23, v2.0.24, v2.0.25, v2.0.9, v2.1.0,
 v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.1
1, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.
3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v
2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6,
v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2
.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2,
v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.
17, v2.7.18, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.2, v2.8.3, v2.8.4, v2.8.
5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - egeloen/lucene-search-bundle 1.0.2 requires symfony/framework-bundle ~2.0 -> satisfiable by symfony/framework-bundle[2.0.7, v2.0.10, v
2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.18, v2.0.19, v2.0.20, v2.0.21, v2.0.22, v2.0.23, v2.0.24, v2.0.25, v2.0.9, v2.1.0,
 v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.1
1, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.
3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v
2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6,
v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2
.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2,
v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.
17, v2.7.18, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.2, v2.8.3, v2.8.4, v2.8.
5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - egeloen/lucene-search-bundle 1.0.0 requires symfony/framework-bundle 2.* -> satisfiable by symfony/framework-bundle[2.0.7, v2.0.10, v2
.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.18, v2.0.19, v2.0.20, v2.0.21, v2.0.22, v2.0.23, v2.0.24, v2.0.25, v2.0.9, v2.1.0,
v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11
, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3
.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2
.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v
2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.
5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v
2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.1
7, v2.7.18, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.2, v2.8.3, v2.8.4, v2.8.5
, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - egeloen/lucene-search-bundle 1.0.1 requires symfony/framework-bundle ~2.1 -> satisfiable by symfony/framework-bundle[v2.1.0, v2.1.1, v
2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2,
 v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3
.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2
.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2
.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.
5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2
.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.1
8, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6,
 v2.8.7, v2.8.8, v2.8.9].
    - don't install symfony/framework-bundle v2.3.0|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.1|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.10|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.11|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.12|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.13|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.14|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.15|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.16|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.17|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.18|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.19|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.2|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.20|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.21|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.22|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.23|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.24|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.25|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.26|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.27|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.28|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.29|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.3|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.30|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.31|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.32|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.33|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.34|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.35|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.36|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.37|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.38|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.39|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.4|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.40|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.41|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.42|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.5|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.6|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.7|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.8|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.3.9|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.4.0|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.4.1|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.4.10|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.4.2|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.4.3|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.4.4|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.4.5|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.4.6|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.4.7|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.4.8|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.4.9|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.5.0|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.5.1|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.5.10|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.5.11|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.5.12|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.5.2|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.5.3|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.5.4|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.5.5|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.5.6|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.5.7|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.5.8|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.5.9|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.6.0|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.6.1|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.6.10|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.6.11|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.6.12|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.6.13|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.6.2|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.6.3|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.6.4|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.6.5|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.6.6|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.6.7|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.6.8|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.6.9|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.0|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.1|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.10|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.11|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.12|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.13|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.14|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.15|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.16|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.17|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.18|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.2|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.3|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.4|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.5|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.6|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.7|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.8|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.7.9|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.8.0|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.8.1|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.8.10|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.8.11|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.8.2|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.8.3|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.8.4|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.8.5|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.8.6|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.8.7|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.8.8|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.8.9|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.2.0|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.2.1|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.2.10|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.2.11|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.2.2|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.2.3|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.2.4|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.2.5|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.2.6|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.2.7|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.2.8|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.2.9|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.0.10|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.0.12|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.0.13|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.0.14|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.0.15|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.0.16|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.0.19|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.0.20|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.0.21|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.0.22|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.0.23|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.0.24|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.0.25|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.0.9|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.1.0|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.1.1|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.1.10|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.1.11|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.1.12|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.1.13|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.1.2|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.1.3|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.1.4|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.1.5|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.1.6|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.1.7|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.1.8|don't install symfony/symfony v3.0.0
    - don't install symfony/framework-bundle v2.1.9|don't install symfony/symfony v3.0.0
    - Installation request for symfony/symfony 3.0.* -> satisfiable by symfony/symfony[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.
6, v3.0.7, v3.0.8, v3.0.9].
    - Installation request for egeloen/lucene-search-bundle ~1.0 -> satisfiable by egeloen/lucene-search-bundle[1.0.0, 1.0.1, 1.0.2, 1.0.3].


Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**And here'is my composer.json file :**

{
    "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-4": { "": "src/" },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
    },
    "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.0.*",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "symfony/assetic-bundle": "^2.7.1",
        "stof/doctrine-extensions-bundle": "^1.2",
        "doctrine/doctrine-fixtures-bundle": "^2.3",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "twig/extensions": "^1.3",
        "egeloen/lucene-search-bundle": "~1.0",
        "zendframework/zendsearch": "dev-master"
    },
    "require-dev": {
        "sensio/generator-bundle": "~3.0",
        "symfony/phpunit-bridge": "~2.7"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ]
    },
    "config": {
        "bin-dir": "bin",
        "platform": {
            "php": "5.5.9"
        }
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "3.0.*"
        }
    },
    "repositories": {
        "packagist": { "url": "https://packagist.org", "type": "composer" }
    }
}

**Comment by egeloen** [comment]
Ok, so after re-reading your post, I think you should try the `2.x` version of the bundle instead. It should fix your issue.

**Comment by egeloen** [comment]
ping @leperse :)

**Comment by NodokaMurmevent** [comment]
Symfony 3.2.1
same problem i have try with :
```
        "egeloen/lucene-search-bundle": "~2.0",
        "zendframework/zendsearch": "dev-master"
```

and symfony return : 
```
  Problem 1
    - egeloen/lucene-search-bundle 2.0.1 requires zendframework/zendsearch ^2.0@rc -> satisfiable by zendframework/zendsearch[2.0.0rc3, 2.0.0rc4, 2.0.0rc5, 2.0.0rc6] but these conflict with your requirements or minimum-stability.
    - symfony/framework-bundle v2.0.18 requires symfony/dependency-injection v2.0.18 -> no matching package found.
    - symfony/framework-bundle v2.0.17 requires symfony/dependency-injection v2.0.17 -> no matching package found.
    - symfony/framework-bundle 2.0.7 requires symfony/translator 2.0.7 -> no matching package found.
    - Installation request for egeloen/lucene-search-bundle ~2.0 -> satisfiable by egeloen/lucene-search-bundle[2.0.0, 2.0.1].
    - Conclusion: remove symfony/symfony v3.2.1
    - Conclusion: don't install symfony/symfony v3.2.1
    - egeloen/lucene-search-bundle 2.0.0 requires symfony/framework-bundle ~2.0 -> satisfiable by symfony/framework-bundle[2.0.7, v2.0.10, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.18, v2.0.19, v2.0.20, v2.0.21, v2.0.22, v2.0.23, v2.0.24, v2.0.25, v2.0.9, v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - don't install symfony/framework-bundle v2.7.0|don't install symfony/symfony v3.2.0
[...]
    - don't install symfony/framework-bundle v2.0.9|don't install symfony/symfony v3.2.0
    - Installation request for symfony/symfony ^3.2 -> satisfiable by symfony/symfony[v3.2.0, v3.2.1].

```

**Comment by egeloen** [comment]
@leperse @NodokaMurmevent Your issue has been explained in 45ccbedc6d5668abd5c1aec0544405357babc0c6
